repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        exclude: ^examples/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff
        exclude: ^examples/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: ["--config-file=pyproject.toml"]
        additional_dependencies:
          - types-requests
          - typer
          - requests
        exclude: ^examples/

  - repo: local
    hooks:
      - id: forbid-korean
        name: Forbid Korean Characters
        entry: bash -c 'if grep -RIl --exclude-dir=.venv --exclude-dir=.git -n "[가-힣]" docs src README.md CHANGELOG.md; then echo "Korean characters detected. Please use English only."; exit 1; fi'
        language: system
        pass_filenames: false
        stages: [commit]
