site_name: Azure Functions Doctor for Python
site_description: A diagnostic tool for Python Azure Functions
site_author: Yeongseon Choe
repo_url: https://github.com/yeongseon/azure-functions-doctor-for-python
site_url: https://yeongseon.github.io/azure-functions-doctor-for-python/

theme:
  name: material
  logo: logo_assets/logo.png
  favicon: logo_assets/logo_favicon_16px.png

nav:
  - Home: index.md
  - CLI Usage: usage.md
  - Diagnostics: diagnostics.md
  - Rules: rules.md
  - Handlers: handlers.md
  - Development: development.md
  - API Reference: api.md
  - Release Process: release_process.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_signature: true
            show_root_full_path: false
            merge_init_into_class: true
