#!/usr/bin/env python3
"""Regenerate the Rule Table in ``docs/rule_inventory.md`` from ``v2.json``.

The authoritative ruleset lives in
``src/azure_functions_doctor/assets/rules/v2.json``. This script regenerates the
``## Rule Table`` section (and its "last generated" stamp) so the inventory
never drifts from the shipped rules. Hand-authored sections such as
``## Rule Types`` and ``## False-positive Risk`` are preserved untouched.

Usage:
    python scripts/gen_rule_inventory.py          # rewrite the file in place
    python scripts/gen_rule_inventory.py --check   # exit 1 if it would change
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RULES_JSON = ROOT / "src" / "azure_functions_doctor" / "assets" / "rules" / "v2.json"
INVENTORY_MD = ROOT / "docs" / "rule_inventory.md"

TABLE_HEADER = "## Rule Table"
NEXT_SECTION = "## Rule Types"
STAMP_PREFIX = "<!-- generated by scripts/gen_rule_inventory.py"


def _profile(rule: dict) -> str:
    # A rule runs in the 'minimal' profile only when required; every rule runs
    # in 'full'. Mirrors Doctor._filter_rules in doctor.py.
    return "minimal, full" if rule.get("required", False) else "full"


def _render_table(rules: list[dict]) -> str:
    lines = [
        TABLE_HEADER,
        "",
        f"{STAMP_PREFIX} — do not edit this table by hand -->",
        "",
        "| Rule ID | Label | Category | Section | Type | Required | Profile |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for rule in rules:
        required = "Yes" if rule.get("required", False) else "No"
        lines.append(
            f"| `{rule['id']}` | {rule.get('label', '')} | {rule.get('category', '')} "
            f"| {rule.get('section', '')} | `{rule.get('type', '')}` | {required} "
            f"| {_profile(rule)} |"
        )
    lines.append("")
    return "\n".join(lines)


def _build(rules: list[dict], current: str) -> str:
    start = current.index(TABLE_HEADER)
    end = current.index(NEXT_SECTION)
    return current[:start] + _render_table(rules) + "\n" + current[end:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail if regeneration would change the file"
    )
    args = parser.parse_args()

    rules = json.loads(RULES_JSON.read_text(encoding="utf-8"))
    current = INVENTORY_MD.read_text(encoding="utf-8")
    updated = _build(rules, current)

    if args.check:
        if updated != current:
            print(
                "docs/rule_inventory.md is out of date. Run: python scripts/gen_rule_inventory.py"
            )
            return 1
        print("docs/rule_inventory.md is up to date.")
        return 0

    if updated != current:
        INVENTORY_MD.write_text(updated, encoding="utf-8")
        print(f"Regenerated docs/rule_inventory.md ({len(rules)} rules).")
    else:
        print("docs/rule_inventory.md already up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
